# Generated by Django 4.2.23 on 2025-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailerUrl',
            field=models.URLField(null=True),
        ),
    ]
