# Generated by Django 4.2.23 on 2025-07-25 14:53

import django.core.validators
from django.db import migrations, models
import streaming.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_genre_name_alter_movie_file_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to=streaming.models.movie_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=streaming.models.poster_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
