# Generated by Django 4.2.23 on 2025-07-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_alter_movie_file_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
