# Generated by Django 4.2.23 on 2025-08-01 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
