# Generated by Django 4.2.23 on 2025-08-02 09:43

import django.core.validators
from django.db import migrations, models
import streaming.models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_alter_movie_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=streaming.models.movie_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi'])]),
        ),
    ]
