# Generated by Django 4.2.23 on 2025-08-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_alter_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hls_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
