# Generated by Django 4.2.23 on 2025-08-02 16:47

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_icon.png', upload_to=accounts.utils.user_profile_picture_upload_path),
        ),
    ]
